feat: add support for Page.ResetNavigationHistory
go-rod/rod pull request #1087
Opened 2024-07-04 12:38 UTC by jackcipher

# Add ResetNavigationHistory functionality

## Description

This PR adds a new function `ResetNavigationHistory` to the `Page` struct, along with its `Must` variant `MustResetNavigationHistory`. This feature allows users to clear the navigation history of a page, which is particularly useful when pages are reused in a pool.

## Changes

1. Added `ResetNavigationHistory` method to `Page` struct in `page.go`
2. Added `MustResetNavigationHistory` method to `Page` struct in `must.go`
3. Added a new test function `TestPageResetNavigationHistory` in `page_test.go`

## Motivation

When pages are reused in a pool, the navigation history accumulates over time. This can lead to unexpected behavior and potentially impact performance. The ability to reset the navigation history provides more control over the page state, especially in scenarios where a clean slate is desired for each new use of a pooled page.

## Usage
Users can now reset the navigation history of a page like this:

```golang
err := page.ResetNavigationHistory()
```

Or using the Must variant:

```golang
page.MustResetNavigationHistory()
```

2024-07-06 05:32 UTC, ysmood approved these changes
LGTM

2024-07-06 05:32 UTC, ysmood commented on page_test.go
> +	g.True(err != nil)
```suggestion
	g.Err(err)
```

2024-07-06 13:34 UTC, jackcipher commented
I've cleaned up the commits. The changes are now based on the latest main branch. Could you please review the updated PR and consider re-approving if everything looks good?

2024-07-09 04:01 UTC, ysmood requested changes

2024-07-09 04:01 UTC, ysmood commented on .gitignore
> +/.idea
Please put this in your global gitignore, not in a specific project.

```suggestion
```

2024-07-09 04:01 UTC, ysmood commented on page.go
> +				case dst <- msg.(*Message): // nolint: forcetypeassert
```suggestion
				case dst <- msg.(*Message): //nolint: forcetypeassert
```

2024-07-10 14:26 UTC, jackcipher commented
Hi, I've resolved the reviews.
Can you take another look at this PR and let me know if there's anything else needed before we can proceed with merging?

2024-07-11 09:59 UTC, ysmood approved these changes

2024-07-11 09:59 UTC, merged