examples vs puppeteer
go-rod/rod pull request #219
Opened 2020-09-15 22:49 UTC by gaoyang-china

两个puppeteer例子

2020-09-16 05:18 UTC, ysmood commented
文件格式是，每个例子一个文件夹，每个文件都叫 main.go：

![image](https://user-images.githubusercontent.com/1415488/93295070-2d8f4b00-f827-11ea-906d-683faf932128.png)

只有这样才可以直接 go run 运行每个文件。这跟 c++ 是一样的，每个文件夹下只可以有一个 `func main()` 函数

2020-09-16 05:25 UTC, ysmood requested changes
请拷贝一份 lib/examples/compare-chromedp/README.md 到你这个文件夹，把里面的表改成 puppeteer 对应的

2020-09-18 00:24 UTC, ysmood requested changes

2020-09-18 00:24 UTC, ysmood commented on lib/examples/compare-puppeteer/pdf/pdf.go
> +	}
这段代码可以换成 `page.MustPDF("hn.pdf")` 默认就是 letter format，不需要再设置 scale 之类的了

2020-09-18 00:24 UTC, ysmood commented on lib/examples/compare-puppeteer/pdf/pdf.go
> +	err := page.Navigate("https://www.google.com")
puppeteer 用的网页是 https://news.ycombinator.com

2020-09-20 22:46 UTC, gaoyang-china commented on lib/examples/compare-puppeteer/pdf/pdf.go
> +	err := page.Navigate("https://www.google.com")
好的，谢谢，我去处理一下

2020-09-23 02:29 UTC, ysmood requested changes

2020-09-23 02:29 UTC, ysmood commented on lib/examples/compare-puppeteer/pdf/main.go
> +	wait()
这段没必要写这么复杂，用 `page.MustWaitRequestIdle` 替换调比较好。

2020-09-23 02:29 UTC, ysmood commented on lib/examples/compare-puppeteer/pdf/main.go
> +	pdf,_:= page.PDF(&parameters)
请替换成 `page.MustPDF("hn.pdf")`

2020-09-23 02:29 UTC, ysmood commented on lib/examples/compare-puppeteer/screenshot/main.go
> +	var e proto.NetworkResponseReceived
请替换成 `page.MustWaitRequestIdle`

2021-02-01 10:42 UTC, closed without merging