Add browser flag to testing
go-rod/rod pull request #324
Opened 2020-12-24 20:44 UTC by infinitepr0

The reason this has been proposed is as follows:

- Many times, I may not wish to download the latest version of chromium, due to bandwidth restrictions.
- I may wish to test the library on a particular version of the browser of my choosing.

For these reasons, the PR provides a flag to specify while testing:
```bash
go test -v --browser-bin=<command to launch browser>
```
to set the browser to use to run tests.

2020-12-25 05:35 UTC, ysmood requested changes

2020-12-25 05:35 UTC, ysmood commented on .github/CONTRIBUTING.md
> +To use a locally installed browser, instead of downloading the latest version of chromium every time while running tests, use the `--browser-bin=<command to launch browser>` flag.
```suggestion
You can use the `-browser-bin` flag to specify a custom browser executable path:
```

2020-12-25 05:35 UTC, ysmood commented on .github/CONTRIBUTING.md
> +go test -v --browser-bin=google-chrome
```suggestion
go test -v --browser-bin=/path/to/browser
```

Not just chrome, user can choose edge

2020-12-25 05:35 UTC, ysmood commented on setup_test.go
> +	if !(bin != "" || utils.FileExists("/.dockerenv") || utils.FileExists("/.containerenv")) {
```suggestion
	const notInContainer = !(utils.FileExists("/.dockerenv") || utils.FileExists("/.containerenv"))
	if bin == "" && notInContainer {
```

2020-12-25 07:17 UTC, infinitepr0 commented
I can't do the linting part, since
1. I absolutely hate node.js
2. I'm getting the following error on trying: 
```
2020/12/25 12:45:25 setup project...
node: error while loading shared libraries: libicui18n.so.68: cannot open shared object file: No such file or directory
panic: exit status 127

goroutine 1 [running]:
github.com/go-rod/rod/lib/utils.E(...)
        /home/infinitepro/GitHub/infinitepr0/rod/lib/utils/utils.go:63
github.com/go-rod/rod/lib/utils.Exec(0x534ab3, 0x3, 0xc00008dee0, 0x6, 0x6)
        /home/infinitepro/GitHub/infinitepr0/rod/lib/utils/utils.go:341 +0x165
main.nodejsDeps()
        /home/infinitepro/GitHub/infinitepr0/rod/lib/utils/setup/main.go:25 +0x132
main.main()
        /home/infinitepro/GitHub/infinitepr0/rod/lib/utils/setup/main.go:13 +0x65
exit status 2
browser.go:1: running "go": exit status 1
```

Can you please do it for me? Thanks!

2020-12-25 07:52 UTC, ysmood commented
Sure, let me handle it.

2020-12-26 11:59 UTC, infinitepr0 commented
> Sure, let me handle it.

It's fine, I handled it (had to full upgrade my system to get the lib files to work). Please review it when free!

2020-12-26 13:12 UTC, ysmood approved these changes

2020-12-26 13:14 UTC, merged