fix xvfb passing multiple parameters
go-rod/rod pull request #402
Opened 2021-05-04 13:16 UTC by SanFenZuiCom

fix flagXVFB does not add to xvfb-run command, and add multiple parameters.

2021-05-04 13:51 UTC, ysmood requested changes
Please fix the CI error.

Please update this method:

https://github.com/go-rod/rod/blob/47eeb7a4e5573942abcf38a5e8a3ce7445bdd936/lib/launcher/launcher.go#L215-L218/

Make it something like:

```go
func (l *Launcher) XVFB(args string...) *Launcher {
```

2021-05-06 21:15 UTC, BenjaminB64 commented
I submit a PR on your master @SanFenZuiCom https://github.com/SanFenZuiCom/rod/pull/1

2021-05-07 07:10 UTC, SanFenZuiCom commented
> I submit a PR on your master @SanFenZuiCom [SanFenZuiCom#1](https://github.com/SanFenZuiCom/rod/pull/1)

Thanks a lot.There seems to be something wrong with my git merge.

2021-05-07 07:26 UTC, ysmood requested changes
There should be no changes for files like "go.mod".

Google "rebase upstream master"

2021-05-07 07:26 UTC, ysmood commented on lib/examples/remote-launch/main.go
> -
Don't remove this line

2021-05-07 07:26 UTC, ysmood commented on lib/examples/remote-launch/main.go
> -
Don't remove this line

2021-05-07 07:26 UTC, ysmood commented on lib/examples/remote-launch/main.go
> -
Don't remove this line

2021-05-07 07:26 UTC, ysmood commented on lib/examples/remote-launch/main.go
> +	l.NoSandbox(true)
```suggestion
	l.NoSandbox(true)
```

2021-05-07 07:26 UTC, ysmood commented on lib/examples/remote-launch/main.go
> +	l.Headless(false)
```suggestion
	// Manipulate flags like the example in examples_test.go
	l.Set("any-flag").Delete("any-flag")

	// Launch with headful mode
	l.Headless(false).XVFB("--server-num=5", "--server-args=-screen 0 1600x900x16")
```

2021-05-07 07:47 UTC, ysmood requested changes

2021-05-07 07:47 UTC, ysmood commented on lib/examples/remote-launch/main.go
> -
Don't remove this space line

2021-05-07 07:47 UTC, ysmood commented on lib/examples/remote-launch/main.go
> -
Don't remove this space line

2021-05-07 07:47 UTC, ysmood commented on go.sum
> +github.com/ysmood/leakless v0.7.0/go.mod h1:R8iAXPRaG97QJwqxs74RdwzcRHT1SWCGTNqY8q0JvMQ=
```suggestion
```

2021-05-07 07:47 UTC, ysmood commented on go.mod
> +	github.com/ysmood/leakless v0.7.0
```suggestion
```

2021-05-07 07:47 UTC, ysmood commented on lib/launcher/launcher.go
> +// UserDataDir will use OS tmp dir by default, this folder will usually be cleaned up by the OS after reboot.
```suggestion
```

2021-05-07 11:19 UTC, ysmood commented
Too many problems, I have to merge it manually.

Merged on https://github.com/go-rod/rod/commit/b72ea332d7b54820e442bc2244f91f65b7beae31

2021-05-07 11:19 UTC, closed without merging