allow setting panic func for browsers
go-rod/rod pull request #433
Opened 2021-06-01 07:13 UTC by egonelbre

This adds customizable panic to Browsers.

Note, I'm not sure whether adding it to RaceContext, Mouse, Keyboard and Touch is necessary. But, I can remove them and call their associated page methods.

For Pages, I needed to use the first pages `.e` rather than inherit it from the parents. Adding a `.e` to that type, would make a backwards incompatible change to `Pages` type and make using it more annoying. So, I decided to go the easier route and fallback to `utils.E` when there isn't a suitable page.

Based on #428.
Fixes #424.

2021-06-01 09:21 UTC, egonelbre commented
Btw. is there a nice way to retrigger the github actions without having to update the PR.

I'm not sure whether this is testsuite.

2021-06-01 10:25 UTC, ysmood commented
> Btw. is there a nice way to retrigger the github actions without having to update the PR.
> 
> I'm not sure whether this is testsuite.

Do you mean this?

![image](https://user-images.githubusercontent.com/1415488/120308455-b3481d80-c306-11eb-87d1-e72755a813d5.png)

2021-06-01 12:03 UTC, egonelbre commented
@ysmood I don't have sufficient permissions for it.

2021-06-01 16:13 UTC, egonelbre commented
I ended up repushing.

2021-06-01 16:43 UTC, ysmood commented
> I ended up repushing.

I spend some time checking permission settings, seems like they don't have one for it.

2021-06-02 06:55 UTC, egonelbre commented
Ah, also, this should be ready for review.

2021-06-02 07:17 UTC, ysmood commented
Great! Give some time to review.

2021-06-04 16:56 UTC, ysmood requested changes
> Note, I'm not sure whether adding it to RaceContext, Mouse, Keyboard and Touch is necessary. But, I can remove them and call their associated page methods.

I think it's better to keep the same design as Context, for example, if a user wants to use a custom panic they can do this:

```go
browser.WithPanic(Panic).Hijack()
```

The hijack can just use the `e` from its internal browser object. 

No need to do this:

```
browser.Hijack().WithPanic(Panic)
```

2021-06-04 17:09 UTC, egonelbre commented
@ysmood it's still taking the `e` from the `browser.e`. https://github.com/go-rod/rod/pull/433/commits/965825e46d7c2608c2d9763436b737ce4aa775d7. There's no separate `WithPanic`.

Just to clarify whether I understand you correctly. It would be fine to call `r.browser.e(` in the methods. And the same goes for RaceContext, Mouse, Keyboard and Touch?

2021-06-04 17:17 UTC, ysmood commented
> Just to clarify whether I understand you correctly. It would be fine to call r.browser.e( in the methods. And the same goes for RaceContext, Mouse, Keyboard and Touch?

Yes, the design style is that reduce private states if possible.

2021-06-04 18:48 UTC, egonelbre commented
Hopefully, this is more aligned with what you had in mind.

2021-06-04 19:31 UTC, ysmood requested changes
Good job, almost there!

I think you forget to add the `WithPanic` methods for `Page` and `Element` in the `must.go` file?

2021-06-05 16:22 UTC, ysmood approved these changes

2021-06-05 16:23 UTC, merged