Add GetXPath method to Element
go-rod/rod pull request #697
Opened 2022-08-23 12:47 UTC by alexferrari88

This PR adds the `GetXPath` method to the `Element` struct.
It allows retrieving the XPath of an element by running the same JS used by Chrome Developer Tools. 

It can be useful if one needs to retrieve the XPath of elements that can only be selected by text or tag. It is based on [playwright-dom-path](https://github.com/alexferrari88/playwright-DOMPath) _(full disclosure: this is a package of mine)_.

On StackOverflow, you can find many people asking how to do this in playwright or selenium so it would be handy to have it in rod as well.

2022-08-25 08:40 UTC, ysmood requested changes
Looks good to me, it just needs some polishments.

2022-08-25 08:40 UTC, ysmood commented on element.go
> +//	/________/                                   /________/
I think this change is not related to this PR, can we remove it?

2022-08-25 08:40 UTC, ysmood commented on element.go
> +	script := "(optimized) => { class Step { value; optimized; constructor(value, optimized) { this.value = value; this.optimized = optimized || false; } toString() { return this.value; } } const xPathV
Can you add this helper to this file:

https://github.com/go-rod/rod/blob/master/lib/js/helper.js

2022-08-26 01:42 UTC, alexferrari88 commented
I have put the function in the helper

2022-08-26 04:28 UTC, alexferrari88 commented
I see that after you synced this with master, the test in now failing. I'm working on it to fix it.

2022-08-27 00:06 UTC, ysmood requested changes
The eslint failed in the CI, please fix it: https://github.com/go-rod/rod/runs/8046314554?check_suite_focus=true#step:5:40

2022-08-27 04:19 UTC, alexferrari88 commented
> The eslint failed in the CI, please fix it: https://github.com/go-rod/rod/runs/8046314554?check_suite_focus=true#step:5:40

done

2022-08-27 13:45 UTC, ysmood requested changes
The PR looks good to me, can you pull the latest maser and resolve the conflict?

2022-08-28 03:56 UTC, alexferrari88 commented
> The PR looks good to me, can you pull the latest maser and resolve the conflict?

done!

2022-08-28 05:36 UTC, ysmood requested changes
It's not in sync with the master, can you read the errors in the github check below?

2022-08-28 05:37 UTC, alexferrari88 commented
As for the other PR, I have now merged it, sorry

2022-08-28 06:03 UTC, alexferrari88 commented
I have rebased on master, solved the conflict, and force pushed it. It should be good now.

2022-08-28 06:57 UTC, ysmood requested changes
Can you fix the CI error first?

2022-08-28 07:44 UTC, alexferrari88 commented
any suggestion on how I can make the method GetXPath return an error for testing purposes? So that I can get 100% test coverage

2022-08-28 08:46 UTC, ysmood commented
Use the stub to retuen eval error, read the commemt of stub, it has examples

2022-08-28 12:23 UTC, alexferrari88 commented
> Use the stub to retuen eval error, read the commemt of stub, it has examples

I wanted indeed to use MockClient.StubError but I cannot see what I can pass as proto.Request in this case. I looked for examples in which you used MustEval but that didn't help...

2022-08-28 13:03 UTC, alexferrari88 commented
> Use the stub to retuen eval error, read the commemt of stub, it has examples

I wanted indeed to use MockClient.StubError but I cannot see what I can pass as proto.Request in this case. I looked for examples in which you used MustEval but that didn't help...

2022-08-28 13:14 UTC, alexferrari88 commented
Finally everything seems to be ok!

2022-08-28 14:00 UTC, ysmood approved these changes
Nice job!

2022-08-28 14:02 UTC, ysmood commented
But it still has some conflict with the master branch, can you resolve it?

2022-08-28 14:03 UTC, ysmood requested changes
But it still has some conflict with the master branch, can you resolve it?

2022-08-28 14:04 UTC, ysmood approved these changes

2022-08-28 14:04 UTC, merged