feat(launcher): add IgnoreCerts
go-rod/rod pull request #754
Opened 2022-11-17 11:40 UTC by gnuletik

fixes https://github.com/go-rod/rod/issues/753

2022-11-17 13:50 UTC, ysmood requested changes

2022-11-18 10:41 UTC, gnuletik commented on lib/launcher/launcher.go
> +}
done !

2022-11-18 11:39 UTC, ysmood commented
Still have some lint issues.

2022-11-19 03:01 UTC, ysmood requested changes

2022-11-19 03:01 UTC, ysmood commented on cspell.json
> +        "staticheck"
```suggestion
        "staticcheck"
```

2022-11-19 15:00 UTC, gnuletik commented on cspell.json
> +        "staticheck"
done!

2022-11-20 00:14 UTC, ysmood approved these changes
LGTM!

2022-11-20 00:19 UTC, merged