`Element.ShadowRoot` returns error when `ShadowRoots` is empty
go-rod/rod pull request #788
Opened 2023-01-11 19:25 UTC by pcen

# Development guide

[Link](https://github.com/go-rod/rod/blob/master/.github/CONTRIBUTING.md)

## Test on local before making the PR

```bash
go run ./lib/utils/simple-check
```

2023-01-12 01:54 UTC, ysmood requested changes
Please add a unit test for it. Check the development guide for how to test the project.

2023-01-12 01:54 UTC, ysmood commented on element.go
> +	ErrNoShadowRoot = errors.New("element has no shadow root")
Please move it to https://github.com/go-rod/rod/blob/master/error.go

2023-01-13 00:35 UTC, ysmood approved these changes
God job!

2023-01-13 00:50 UTC, ysmood requested changes
Please fix the ci coverage error. 

If you don't how please read: https://github.com/go-rod/rod/blob/master/.github/CONTRIBUTING.md

2023-01-13 22:34 UTC, pcen commented
merging should close https://github.com/go-rod/rod/issues/787

2023-01-14 01:29 UTC, ysmood approved these changes

2023-01-14 01:36 UTC, merged